### PR TITLE
Adding cheatsheet page

### PR DESCRIPTION
**Pull request by hackyguru**
Hosting some important CTA links in docs.waku.org/cheatsheet to improve discoverability and sharing of cheatsheet

### CODE REVIEW

**Comment by hackyguru** [comment]
thanks for flagging @LordGhostX 

- yes, you're right - I will replace this with a generic cheatsheet.
- reason why i added the links to idea board, examples and docs is because it is more accessible for users from their browsers (they don't have to scan QR codes but just click it. since we don't use the sidebar used in the documentation in this page, it's nice to have these important links highlighted. 
- it's also super easy to reference it during talks or networking. we could just say 'head over to docs.waku.com/cheatsheets' and this will help us be 100% sure that they'll have a chance to look at the idea board even if they don't dig much into the docs

**Comment by hackyguru** [comment]
for navigation, i'd leave it upto you :) i tried thinking of a perfect spot to place it was not able to arrive to a conclusion - so i'd prefer you to pick the spot @LordGhostX

**Comment by LordGhostX** [comment]
Thanks for the clarification, sounds okay to me 👍 

Lemme know when you're done with the changes so I'll just setup the navigation and deploy 🚀

**Comment by LordGhostX** [comment]
superseded by https://github.com/waku-org/docs.waku.org/pull/192

**Pull request closed without merging**
