### PR TITLE
Add research menu and relevant docs

### PR DESCRIPTION
**Pull request by jinhojang6**
Handle issue https://github.com/waku-org/docs.waku.org/issues/155

### CODE REVIEW

**Comment by fryorcraken** [comment]
Did you just copy pasted the files?

It might be better to use git submodules.

**Comment by fryorcraken** [comment]
I can see 3 ways of doing things:
1. git submodules
2. A build script that pulls latest master at build time
3. copy (manually or script) files locally with some manual action from developer and push them to repo (what is done now).

**Comment by fryorcraken** [comment]
I'll try locally later. @LordGhostX please also review.

**Review by LordGhostX — APPROVED** [review]
Screenshot 2024-01-24 at 20 44 07

I find this approach appealing and it works very fine

**Comment by fryorcraken** [comment]
> "incentivization" -> "Incentivization"

```
---
title: Incentivization
---
```

Should be added to the incentivization.md file in the research repo cc @jm-clius 

> Also, the docs site uses British English, so "Incentivization" should be written as "Incentivisation", running yarn check:spell should throw errors because of this

The issue is that this needs to be fixed upstream in the research repo.

@jm-clius how do you feel about adding a spellcheck in the research repo? it helps with typo but does add an extra step.

We preferably would want to do that directly in the research repo so it does not block the PR in the docs repo.

Same question for @Ivansete-status re nwaku repo.

Current cspell error output:

```

/home/fryorcraken/src/waku-org/docs.waku.org/docs/research/benchmarks/postgres-adoption.md:49:24 - Unknown word (pubsubtopic)
/home/fryorcraken/src/waku-org/docs.waku.org/docs/research/benchmarks/postgres-adoption.md:50:86 - Unknown word (pubsubtopic)
/home/fryorcraken/src/waku-org/docs.waku.org/docs/research/benchmarks/postgres-adoption.md:69:25 - Unknown word (jmeter)
/home/fryorcraken/src/waku-org/docs.waku.org/docs/research/benchmarks/postgres-adoption.md:80:9 - Unknown word (jmeter)
/home/fryorcraken/src/waku-org/docs.waku.org/docs/research/benchmarks/postgres-adoption.md:83:111 - Unknown word (jmeter)
/home/fryorcraken/src/waku-org/docs.waku.org/docs/research/benchmarks/postgres-adoption.md:85:9 - Unknown word (jmeter)
/home/fryorcraken/src/waku-org/docs.waku.org/docs/research/benchmarks/postgres-adoption.md:89:180 - Unknown word (jmeter)
/home/fryorcraken/src/waku-org/docs.waku.org/docs/research/benchmarks/postgres-adoption.md:95:54 - Unknown word (analyzed)
/home/fryorcraken/src/waku-org/docs.waku.org/docs/research/benchmarks/postgres-adoption.md:112:98 - Unknown word (queryc)
/home/fryorcraken/src/waku-org/docs.waku.org/docs/research/benchmarks/postgres-adoption.md:112:247 - Unknown word (wakudev)
/home/fryorcraken/src/waku-org/docs.waku.org/docs/research/benchmarks/postgres-adoption.md:112:260 - Unknown word (statusim)
/home/fryorcraken/src/waku-org/docs.waku.org/docs/research/benchmarks/postgres-adoption.md:158:98 - Unknown word (queryc)
/home/fryorcraken/src/waku-org/docs.waku.org/docs/research/benchmarks/postgres-adoption.md:158:247 - Unknown word (wakudev)
/home/fryorcraken/src/waku-org/docs.waku.org/docs/research/benchmarks/postgres-adoption.md:158:260 - Unknown word (statusim)
/home/fryorcraken/src/waku-org/docs.waku.org/docs/research/benchmarks/postgres-adoption.md:196:47 - Unknown word (chronos)
/home/fryorcraken/src/waku-org/docs.waku.org/docs/research/benchmarks/postgres-adoption.md:198:360 - Unknown word (libpqis)
/home/fryorcraken/src/waku-org/docs.waku.org/docs/research/benchmarks/postgres-adoption.md:213:164 - Unknown word (Conn)
/home/fryorcraken/src/waku-org/docs.waku.org/docs/research/benchmarks/postgres-adoption.md:213:282 - Unknown word (messageindex)
/home/fryorcraken/src/waku-org/docs.waku.org/docs/research/benchmarks/postgres-adoption.md:213:312 - Unknown word (storedat)
/home/fryorcraken/src/waku-org/docs.waku.org/docs/research/benchmarks/postgres-adoption.md:213:326 - Unknown word (pubsubtopic)
/home/fryorcraken/src/waku-org/docs.waku.org/docs/research/benchmarks/postgres-adoption.md:220:87 - Unknown word (wakudev)
40/42 ./docs/research/research-and-studies/incentivization.md 73.87ms X
/home/fryorcraken/src/waku-org/docs.waku.org/docs/research/research-and-studies/incentivization.md:2:8 - Unknown word (Incentivization)
/home/fryorcraken/src/waku-org/docs.waku.org/docs/research/research-and-studies/incentivization.md:7:11 - Unknown word (incentivization)
/home/fryorcraken/src/waku-org/docs.waku.org/docs/research/research-and-studies/incentivization.md:7:69 - Unknown word (behavior)
/home/fryorcraken/src/waku-org/docs.waku.org/docs/research/research-and-studies/incentivization.md:15:3 - Unknown word (Incentivization)
/home/fryorcraken/src/waku-org/docs.waku.org/docs/research/research-and-studies/incentivization.md:16:4 - Unknown word (Incentivization)
/home/fryorcraken/src/waku-org/docs.waku.org/docs/research/research-and-studies/incentivization.md:18:17 - Unknown word (incentivization)
/home/fryorcraken/src/waku-org/docs.waku.org/docs/research/research-and-studies/incentivization.md:53:100 - Unknown word (misbehavior)
/home/fryorcraken/src/waku-org/docs.waku.org/docs/research/research-and-studies/incentivization.md:57:72 - Unknown word (Filecoin)
/home/fryorcraken/src/waku-org/docs.waku.org/docs/research/research-and-studies/incentivization.md:57:82 - Unknown word (IPFS)
/home/fryorcraken/src/waku-org/docs.waku.org/docs/research/research-and-studies/incentivization.md:83:86 - Unknown word (behavior)
/home/fryorcraken/src/waku-org/docs.waku.org/docs/research/research-and-studies/incentivization.md:84:62 - Unknown word (behavior)
/home/fryorcraken/src/waku-org/docs.waku.org/docs/research/research-and-studies/incentivization.md:103:14 - Unknown word (incentivization)
/home/fryorcraken/src/waku-org/docs.waku.org/docs/research/research-and-studies/incentivization.md:120:54 - Unknown word (txid)
/home/fryorcraken/src/waku-org/docs.waku.org/docs/research/research-and-studies/incentivization.md:127:85 - Unknown word (txid)
/home/fryorcraken/src/waku-org/docs.waku.org/docs/research/research-and-studies/incentivization.md:128:32 - Unknown word (txid)
/home/fryorcraken/src/waku-org/docs.waku.org/docs/research/research-and-studies/incentivization.md:152:24 - Unknown word (txid)
/home/fryorcraken/src/waku-org/docs.waku.org/docs/research/research-and-studies/incentivization.md:156:9 - Unknown word (txid)
/home/fryorcraken/src/waku-org/docs.waku.org/docs/research/research-and-studies/incentivization.md:163:80 - Unknown word (Hopr)
/home/fryorcraken/src/waku-org/docs.waku.org/docs/research/research-and-studies/incentivization.md:172:106 - Unknown word (deanonymize)
/home/fryorcraken/src/waku-org/docs.waku.org/docs/research/research-and-studies/incentivization.md:186:17 - Unknown word (honors)
/home/fryorcraken/src/waku-org/docs.waku.org/docs/research/research-and-studies/incentivization.md:227:14 - Unknown word (incentivization)
```

If cspell can be added to nwaku and research, then the matching cspell config files should be pulled in too:

https://cspell.org/docs/getting-started/#command-lint--spell-checking
> Configuration file to use.  By default cspell looks for cspell.json in the current directory.

So that once spelling is sorted in nwaku/research repo, it will work here.

**Comment by fryorcraken** [comment]
@jm-clius if you are able to do the same as https://github.com/waku-org/nwaku/pull/2383 then we could get it shipped!

**Comment by jm-clius** [comment]
Done in https://github.com/waku-org/research/pull/83
Have fixed the incentivisation doc by adding a title and changing to British spelling. I've also added a cspell list of spell exceptions.

**Comment by fryorcraken** [comment]
@jinhojang6 @LordGhostX . Hanno and Ivan have added cspell checks. Can you now review and see if we can merge?

**Comment by LordGhostX** [comment]
> @jinhojang6 @LordGhostX . Hanno and Ivan have added cspell checks. Can you now review and see if we can merge?

@fryorcraken we're good to merge now 👍 

@jinhojang6 I added `fs.rmSync` to remove the `research` directory before downloading the remote files (to handle any file structure changes)

**Pull request merged**
